### ISSUE TITLE
Text values are accepted for numeric questions

### ISSUE THREAD

**Issue by rgmerck** [surveydown-dev/surveydown#120]
### Bug description

When you define a sd_question with type  = 'numeric', I would expect that surveydown confirms that the input from the user is indeed numeric only. However, no such check happens. You can use your keyboard and type text and surveydown will accept the answer.

### Steps to reproduce

create a sd_question with type=numeric
Confirm that you can type text and go to "next" without numerical values entered

### Expected behavior

only numerical values should be accepted. Either at the input level (not accepting anything else but numeric characters) or before going to the next page.

### Actual behavior

text can be entered

### Your environment

- Rstudio
- Ubuntu 24.04

**Comment by jhelvy** [comment]
I cannot replicate this. If you try the [question types demo survey](https://surveydown.shinyapps.io/types/), on the page that has the different question types, the numeric type question will not let me enter text. I can only enter numbers. I also just tried a one-question survey with `type = "numeric"` and I can only enter numbers in it.

That said, we do still have it on our roadmap to do more formal type validation, meaning we will not let the user go forward in the survey if they entered an incorrect input type based on the question type.

**Comment by jhelvy** [comment]
I'm closing this as I cannot replicate the error.
