### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by chris-gaskell** [surveydown-dev/surveydown#81]
Hi 

I think I have a problem with rendering the document. For some reason, it does not consistently render. It can take up to 4-5 attempts for it to work for me, although there is nothing I change between attempts (screenshot below of view when it does not render).

I have tried updating Quarto and RStudio but no change.

Hopefully an easy one and just something that I am doing wrong.

Thanks,
Chris

<img width="1955" alt="Screenshot 2024-08-29 at 16 57 23" src="https://github.com/user-attachments/assets/7b9a3eb3-4e8d-4254-8381-a0d6667b83ee">

<img width="629" alt="Screenshot 2024-08-29 at 17 00 56" src="https://github.com/user-attachments/assets/fa7d1c8f-e110-4b10-bd2e-c1a339625012">

**Comment by jhelvy** [comment]
I'm not sure I'm understanding the issue. It looks like in the screenshot that the survey did render properly. You can see at the end of the terminal that it provides a URL with a localhost. If you navigate in your web browser to that URL, it should show the survey. It doesn't always pop up automatically.

**Comment by chris-gaskell** [comment]
John sorry for that. I can see what you mean now. It works perfectly with the URL, it's just the pop up in R Studio that is a little inconsistent.

Thanks again,
Chris

**Comment by jhelvy** [comment]
Yeah I still haven't been able to figure out what makes it sometimes pop up inside RStudio and other times not. It is not consistent. But I mostly edit in VSCode too now, which always shows the localhost (no pop up).
