### ISSUE TITLE
Reporting and downloading results of surveys

### ISSUE THREAD

**Issue by chris-gaskell** [surveydown-dev/surveydown#85]
**Feature Request for Surveydown**

Currently, when generating output or reports with Surveydown, it would be useful to have additional examples or documentation on how developers can customize the presentation of the report to users.

Additionally, it would be helpful to demonstrate a variety of export options (I have not worked out how to include them having just been unsuccessful in combining the downloadthis package), such as:

- Text File (.txt)
- PDF (.pdf)
- Copy to Clipboard

Thank you for considering this request!

**Comment by jhelvy** [comment]
I'm not quite sure I understand what you mean by customizing the presentation of the reports to users. Are you saying you want to generate a custom report about the responses each user made? 

If you're looking to print out your survey, we recommend setting `show_all_pages = TRUE` in `sd_config()` when you run it locally, which will let you see all of the pages at once so you can print it from Chrome. More [here](https://surveydown.org/config-options#show-all-pages)

**Comment by jhelvy** [comment]
If you're trying to download the data, see the fetch data article: https://surveydown.org/fetch-data

I'm going to close this issue for now as I don't believe this is a bug or problem with the documentation. If you need help with something, please open a thread in the discussion page.
